[build]
builder = "nixpacks"

[deploy]
startCommand = "bin/rails server -b 0.0.0.0 -p ${PORT:-3000}"
healthcheckPath = "/up"
healthcheckTimeout = 300

[phases.setup]
nixPkgs = ["postgresql", "libjemalloc"]
